# For more information: https://laravel.com/docs/sail
version: "3"
services:
  app:
    build:
      context: ./docker/8.4
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: sail-8.4/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-80}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
      CONTAINER_ROLE: app
    volumes:
      - ".:/var/www/html"
    networks:
      sail:
        # http://app.test is an alias
        # chrome won't set cookies on things that aren't FQDN
        aliases:
          - app.test
    depends_on:
      - mysql
      - redis
    entrypoint: "./docker/start.sh"
  scheduler:
    image: sail-8.4/app
    container_name: laravel-scheduler
    depends_on:
      - app
    volumes:
      - ".:/var/www/html"
    environment:
      CONTAINER_ROLE: scheduler
    networks:
      - sail
    entrypoint: "./docker/start.sh"
  queue:
    image: sail-8.4/app
    container_name: laravel-queue
    depends_on:
      - app
      - redis
    volumes:
      - ".:/var/www/html"
    environment:
      CONTAINER_ROLE: queue
    networks:
      - sail
    entrypoint: "./docker/start.sh"
  mysql:
    image: "mariadb"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "sailmysql:/var/lib/mysql"
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
      interval: 10s
  redis:
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "sailredis:/data"
    networks:
      - sail
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
  reverb:
    image: sail-8.4/app
    depends_on:
    - app
    - redis
    volumes:
        - ".:/var/www/html"
    environment:
        CONTAINER_ROLE: reverb
    networks:
        - sail
    ports:
        - '${REVERB_PORT:-8080}:8080'
    entrypoint: "./docker/start.sh"
  # echo:
  #   image: oanhnn/laravel-echo-server
  #   container_name: laravel-echo
  #   restart: unless-stopped
  #   ports:
  #     - 6001:6001
  #   depends_on:
  #     - redis
  #     - app
  #   environment:
  #     LARAVEL_ECHO_SERVER_AUTH_HOST: "http://app"
  #     LARAVEL_ECHO_SERVER_DEBUG: "true"
  #   networks:
  #     sail:
  #       # Make it appear that echo and the app service
  #       # are on the same host `app.test`, just running
  #       # on different ports
  #       aliases:
  #         - app.test
networks:
  sail:
    driver: bridge
volumes:
  sailmysql:
    driver: local
  sailredis:
    driver: local
