  version: "3.4"

  services:
    node:
      image: laravel-node
      container_name: laravel-node
      build:
        context: .
        dockerfile: docker/node.Dockerfile
      depends_on:
        - app
      ports:
       - 8080:8080
      volumes:
        - .:/app:cached
        - /app/vendor
        - /app/node_modules
      entrypoint: ["npm", "run", "prod"]
      networks:
        chimein:    
          aliases:
            - app.test
