name: Bundlewatch

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:
  workflow_dispatch:

env:
  # check production bundle sizes
  MIX_APP_ENV: production
  FORCE_COLOR: 2
  NODE: 16
  CI_REPO_OWNER: umn-latis
  CI_REPO_NAME: chimein2.0

jobs:
  bundlewatch:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3.2.0
        with:
          node-version: "${{ env.NODE }}"

      - name: Install npm dependencies
        run: yarn install --frozen-lockfile

      - name: Run dist
        run: yarn run prod

      - name: Run bundlewatch
        run: yarn run bundlewatch
        env:
          BUNDLEWATCH_GITHUB_TOKEN: "${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}"
          CI_BRANCH_BASE: develop
