name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: cp .env.example .env

      - name: Setup PHP 7.4 to match server
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      - run: composer install --no-interaction --prefer-dist

      - name: Build
        run: docker-compose build

      - name: Start
        run: docker-compose up -d

      - name: Check
        run: |
          docker-compose ps --all

      - run: docker-compose exec -T app ./bin/ci.sh
      - run: yarn install --frozen-lockfile
      - run: yarn run prod
      - run: docker-compose exec -T app php artisan key:generate
      - run: docker-compose exec -T app php artisan migrate:fresh
      - run: docker-compose exec -T app php artisan db:seed

      # - name: Test
      #   run: docker-compose exec -T -e "APP_URL=http://${APP_SERVICE}" -e "DUSK_DRIVER_URL=http://selenium:4444/wd/hub" app php artisan dusk

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: tests/Browser/screenshots

      - name: Upload Console Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: console
          path: tests/Browser/console
