name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup config
        run: |
          cp .env.test .env
          cp docker-compose.test.yml docker-compose.yml
      - name: Build docker
        run: |
          docker-compose build
          docker-compose up --detach
      - name: Check
        run: |
          docker-compose ps --all
      - name: Config App for Dusk
        run: |
          docker-compose exec -T app bin/ci.sh
      - name: Run tests
        env:
          APP_URL: "http://127.0.0.1:8000"
        run: |
          docker-compose exec -T app php artisan dusk
      - name: Logs
        if: ${{ always() }}
        run: |
          docker-compose logs
      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: tests/Browser/screenshots
      - name: Upload Console Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: console
          path: tests/Browser/console
