name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: cp .env.example .env

      - name: Setup PHP 7.4 to match server
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      - run: composer install --no-interaction --prefer-dist

      - name: Build
        run: ./vendor/bin/sail build

      - name: Start
        run: ./vendor/bin/sail up -d

      - name: Check
        run: |
          ./vendor/bin/sail ps --all

      - run: ./vendor/bin/sail ./bin/ci.sh
      - run: yarn install --frozen-lockfile
      - run: yarn run prod
      - run: ./vendor/bin/sail artisan key:generate
      - run: ./vendor/bin/sail artisan migrate:fresh --seed

      - name: Run E2E tests with Cypress
        uses: cypress-io/github-action@v2
        with:
          wait-on: "http://app"
          config: baseUrl=http://app

      - name: Upload test screenshots if any
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload test videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
