name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup config
        run: cp .env.test .env
      - name: Build docker
        run: |
          docker-compose -f docker-compose.test.yml build
          docker-compose -f docker-compose.test.yml up --detach
      - name: Check
        run: docker-compose -f docker-compose.test.yml ps --all
      - name: Generate Key
        run: docker-compose -f docker-compose.test.yml exec -T app php artisan key:generate
      - name: Directory Permissions
        run: |
          docker-compose exec -T app php artisan storage:link
          docker-compose exec -T app chmod -R 777 storage
          docker-compose exec -T app chmod -R 777 bootstrap/cache
          docker-compose exec -T app php artisan config:cache
      - name: Migrate DB
        run: docker-compose -f docker-compose.test.yml exec -T app php artisan migrate:fresh 2>&1
      - name: Run tests
        env:
          APP_URL: "http://127.0.0.1:8000"
        run: |
          docker-compose -f docker-compose.test.yml exec app php artisan dusk
      - name: Logs
        if: ${{ always() }}
        run: |
          docker-compose -f docker-compose.test.yml logs
      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: tests/Browser/screenshots
      - name: Upload Console Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: console
          path: tests/Browser/console
