name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build docker
        run: |
          echo ---Building and starting docker---
          docker-compose -f docker-compose.test.yml build
          docker-compose -f docker-compose.test.yml up --detach
          echo ---Containers up---
      # - name: Create app key
      #   run: |
      #     echo ---Creating app key---
      #     docker-compose exec app php artisan key:generate 2>&1
      #     echo ---App key created---
      - name: Migrate Database
        run: |
          docker-compose exec app php artisan migrate:fresh 2>&1
      - name: Run tests
        run: |
          echo ---Running tests---
          docker-compose exec app php artisan dusk
          echo ---Tests complete---
      - name: The job has failed
        if: ${{ failure() }}
        run: |
          docker-compose logs
